const express = require("express");
const router = express.Router();
const modeRoutes = require("./modeRoutes");
const categoryRoutes = require("./categoryRoutes");
const subCategoryRoutes = require("./subCategoryRoutes");
const productRoutes = require("./productRoutes");
const adminRoutes = require("./adminRoutes");
const userRoutes = require("./userRoutes");
const restaurantRoutes = require("./restaurantRoutes");
router.use("/modes", modeRoutes);
router.use("/category", categoryRoutes);
router.use("/subCategory", subCategoryRoutes);
router.use("/product", productRoutes);
router.use("/admin", adminRoutes);
router.use("/user", userRoutes);
router.use("/restaurant", restaurantRoutes);
module.exports = router;
