const express = require("express");
const router = express.Router();
const modeRoutes = require("./modeRoutes");
const categoryRoutes = require("./categoryRoutes");
const subCategoryRoutes = require("./subCategoryRoutes");
const productRoutes = require("./productRoutes");
router.use("/modes", modeRoutes);
router.use("/category", categoryRoutes);
router.use("/subCategory", subCategoryRoutes);
router.use("/product", productRoutes);
module.exports = router;
