const express = require("express");
const router = express.Router();
// const adminRoutes = require("./adminRoutes");
// const userRoutes = require("./userRoutes");
// const connectionRoutes = require("./connectionRoutes");
// const resumeRoutes = require("./resumeRoutes");
// const companyRoutes = require("./companyRoutes");
// const jobRoutes = require("./jobRoutes");
// const jobApplicationRoutes = require("./jobApplicationRoutes");
// const postRoutes = require("./postRoutes");
// const commentRoutes = require("./commentRoutes");
// const subscriptionRoutes = require("./subscriptionRoutes");
// const paymentRoutes = require("./paymentRoutes");
// const messageRoutes = require("./messageRoutes");
// const reportRoutes = require("./reportRoutes");
// router.use("/admins", adminRoutes);
// router.use("/users", userRoutes);
// router.use("/connections", connectionRoutes);
// router.use("/resumes", resumeRoutes);
// router.use("/companies", companyRoutes);
// router.use("/jobs", jobRoutes);
// router.use("/job-applications", jobApplicationRoutes);
// router.use("/posts", postRoutes);
// router.use("/comments", commentRoutes);
// router.use("/subscriptions", subscriptionRoutes);
// router.use("/payment", paymentRoutes);
// router.use("/messages", messageRoutes);
// router.use("/report", reportRoutes);
module.exports = router;
